name: Python application

on: push
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
    
    env:
      DOCKER_TOKEN: ${{ env.DOCKER_TOKEN }}
    
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "raisanjivj6693" --password-stdin
        docker image build -t raisanjivj6693/pyflask:latest .
        docker push raisanjivj6693/pyflask:latest
